when:
  - event: [push, pull_request, tag]

steps:
  install-deps:
    image: rust:latest
    commands:
      - apt-get update && apt-get install -y libasound2-dev

  check:
    image: rust:latest
    commands:
      - cargo check --workspace --all-targets

  clippy:
    image: rust:latest
    commands:
      - rustup component add clippy
      - cargo clippy --workspace --all-targets -- -D warnings

  test:
    image: rust:latest
    commands:
      - cargo test --workspace --all-targets

  fmt:
    image: rust:latest
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check

  build:
    image: rust:latest
    commands:
      - cargo build --workspace --release
