when:
  - event: [push, pull_request, tag]

variables:
  - &rust-deps |
    apt-get update && apt-get install -y libasound2-dev

steps:
  check:
    image: rust:latest
    commands:
      - *rust-deps
      - cargo check --workspace --all-targets

  clippy:
    image: rust:latest
    commands:
      - *rust-deps
      - rustup component add clippy
      - cargo clippy --workspace --all-targets -- -D warnings

  test:
    image: rust:latest
    commands:
      - *rust-deps
      - cargo test --workspace --all-targets

  fmt:
    image: rust:latest
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check

  build:
    image: rust:latest
    commands:
      - *rust-deps
      - cargo build --workspace --release
