when:
  - event: [push, pull_request, tag]

variables:
  - &rust-deps |
    apt-get update && apt-get install -y libasound2-dev

steps:
  check:
    image: rust:latest
    commands:
      - *rust-deps
      - rustup component add clippy
      - rustup component add rustfmt
      - cargo check --workspace --all-targets
      - cargo clippy --workspace --all-targets -- -D warnings
      - cargo test --workspace --all-targets
